### ISSUE TITLE
Creating user with username `L. Kiesow` fails

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-admin-interface#776]
Looks like the URLs are not encoded properly:
```
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 39: http://localhost:8080/admin-ng/users/L. Kiesow.json                                                                                                     
        at java.net.URI.create(URI.java:883) ~[?:?]                                                                                                                                                                                           
        at org.opencastproject.util.UrlSupport.uri(UrlSupport.java:174) ~[?:?]                                                                                                                                                                
        at org.opencastproject.adminui.endpoint.UsersEndpoint.createUser(UsersEndpoint.java:360) ~[?:?]
```

**Comment by dennis531** [comment]
The post request parameters to `/admin-ng/users` look good:
```
{
	"username": "test1+test1",
	"name": "Test+2",
	"email": "debenz@uos.de",
	"password": "123",
	"roles": "[]"
}
```

This seems like an Opencast bug as the parameter will be created by the [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) which already [encodes the values](https://url.spec.whatwg.org/#interface-urlsearchparams). Encoding with [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) leads to the following problem:

![image](https://github.com/opencast/opencast-admin-interface/assets/44410838/ca09ca56-a6b2-4943-abba-ec80de0a3b28)

In this case, I need to login with the username `Test%20Test`.

**Comment by mtneug** [comment]
Do we want usernames with whitespaces? Are people doing this 😱?

**Comment by lkiesow** [comment]
No, I think we don't want that :D
We should limit frontend and backend to:
```
[0-9a-z_-:][0-9a-z_-:]*
```

**Comment by mtneug** [comment]
> No, I think we don't want that :D We should limit frontend and backend to:
> 
> ```
> [0-9a-z_-:][0-9a-z_-:]*
> ```

[Please don't.](https://github.com/orgs/opencast/discussions/6539#discussioncomment-12541529)
